### ISSUE TITLE
.save  and .update could return key|values they saved/updated

### ISSUE THREAD

**Issue by niksajanjic** [jasonmerino/react-native-simple-store#22]
I suppose we could benefit from returning as _then_ parameter what we just stored using _.save_ and _.update_ if we want to do something else with that data. In case below I want to make sure my data is saved in storage before I can do something else with the data returned from API. Because simple store is Promised based when we want to _.save_ something, our _then_ function doesn't have any parameter. Maybe it would be good to return same properties we passed to _.save_ as _then_ parameter. This is how we need to do it now:

```
import store from 'react-native-simple-store';

fetch('some_URL', options}).then(resp =>
  store.save([['token', `Bearer ${resp.token}`], ['user', resp.user]]))
).then(() =>
  store.get('user')
).then(resp =>
  // do something with user object in my code
)
```

or better option:
```
import store from 'react-native-simple-store';

let temp;

fetch('some_URL', options}).then(resp => {
  temp = resp;
  return store.save([['token', `Bearer ${resp.token}`], ['user', resp.user]]))
}).then(() =>
  // do something with resp which is saved in temp variable
)
```

but it would probably be best to return object with key|value pairs of all the things we just saved/updated:
```
import store from 'react-native-simple-store';

fetch('some_URL', options}).then(resp =>
  store.save([['token', `Bearer ${resp.token}`], ['user', resp.user]]))
).then(resp =>
  // resp should now be { token: 'Bearer some.token.here', user: {...} } and we can continue as we know it's been saved into AsyncStorage
)
```

What do you think? Does this make sense?

**Comment by jasonmerino** [comment]
@niksajanjic I had thought the same thing initially when I was writing this module that the save method could return what you just saved. However, I have been hesitant to do that because that is not how AsyncStorage itself works and I meant this module to be a very minimalistic layer on top of that React Native API.

Another reason for not returning what was saved is that error handling is far trickier than one would hope when working with promises. That being said, with how simple store works now, if you get _any_ value back in a `.then` function directly after a call to `.save` you can be sure that an error has occurred. If we were to return the value that was just saved there would be added complexity regarding error handling.

Given those restraints, to accomplish your first example you could do something like this.

```js
import store from 'react-native-simple-store';

fetch('some_URL', options}).then(resp =>
  store.save([['token', `Bearer ${resp.token}`], ['user', resp.user]]))
  return resp.user
).then(user =>
  // do something with user object in my code
)
```

**Comment by niksajanjic** [comment]
This solution isn't going to work in our case because you immediately return resp.user which means next _then_ is called immediately without knowing if _.save_ method was done successfully or not. I need to return promise from store.save to be able to know if we saved data before I can do anything else in the code or if it ended with error to handle it.

On the other hand I do understand all the reasons why _update_ and _save_ method don't return anything, therefore I will close this issue and use one of the methods explained in my first post. Thank you for your quick and detailed response.
