### ISSUE TITLE
Make docs easier to read

### ISSUE THREAD

**Issue by DZuz14** [jasonmerino/react-native-simple-store#30]
Docs are helpful, but should be split up into different sections, instead of one big promise. I can help out with a pull request for that if needed.

**Comment by jasonmerino** [comment]
That would be really cool. There is an [API reference here](https://github.com/jasonmerino/react-native-simple-store/blob/master/docs/index.md) which are split out by function and generated with every new `npm version`, but I would like some more clarity in the [Example Usage](https://github.com/jasonmerino/react-native-simple-store#example-usage) section of the main README. Since it's purpose is to give folks a quick sample of what it would look like to interact with the library it should be very nice to add clarity in that area.

Feel free to make some adjustments. I'm sure whatever you come up with would be awesome.

Also! If you want to add an additional example with an async/await function that would be cool too.

**Comment by DZuz14** [comment]
Dope salad. Will do. Hopefully get something whipped up over the weekend. Thanks for the new push feature.

**Comment by DZuz14** [comment]
I am still going to get on this. I actually had an interview yesterday that I have been studying the whole past week for, so had to put this on hold. However, I do have a new issue I am going to post here in a few minutes that I could use some help with. 

Understanding that issue will make the docs more complete, as I am unsure how a few things still work.

**Comment by jasonmerino** [comment]
Resolved by #33

**Comment by DZuz14** [comment]
Yoooo. I have no idea how to fix those formatting issues. So annoying. I tried deleting them and changing the tab spaces, and nothing. Any suggestions?

**Comment by jasonmerino** [comment]
Mmmm, I'm not sure why it wouldn't let you. Might be something having to do with the editor you're using. I just pulled it up on my machine and used VSCode's "Convert Indentation to Tabs" option and it seemed to work.
