### ISSUE TITLE
Couldn't read row 0, col 0 from Cursor Window.

### ISSUE THREAD

**Issue by jeffbonasso** [jasonmerino/react-native-simple-store#40]
I am getting the error Can't read row 0, col 0 from Cursor Window. Doing a little research it seems like there may be a limitation of 2MB for sqllite. My assumption are you are using sqllite in this implementation. Not sure how you are using it, but wondering if anyone has come across and if there is a workaround. I am saving some large JSON chunks using this library. The error is only occurring on Android.

**Comment by jasonmerino** [comment]
@jeffbonasso I am calling directly into React Native's `AsyncStorage`. There's no optimizations that this library does to data before saving it. It could very well be that you are hitting a SQLite limitation because according to the RN docs it looks like that may be where `AsyncStorage` saves data.

> [On Android, AsyncStorage will use either RocksDB or SQLite based on what is available.](https://facebook.github.io/react-native/docs/next/asyncstorage.html#docsNav)

From what I can tell there's not a lot I could do to change this for you. Going to close this out. Comment back if you think of anything we can do to help with this.
