### ISSUE TITLE
Does not work with react native 0.59.4

### ISSUE THREAD

**Issue by rauwork** [jasonmerino/react-native-simple-store#54]
update my project to 0.59.4 and now fails

**Comment by oas** [comment]
Yeah, I have the same problem. This is probably due to the use of `AsyncStorage`, which has recently been deprecated:

`ExceptionsManager.js:82 Warning: Async Storage has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/async-storage' instead of 'react-native'. See https://github.com/react-native-community/react-native-async-storage`

**Comment by mikerodham** [comment]
That's because asyncstorage is no longer a part of the core react-native. This was announced in the app as a yellowbox warning. You can see [here](https://facebook.github.io/react-native/docs/asyncstorage). You may have to install [this package](https://github.com/react-native-community/react-native-async-storage) to get it working.

**Comment by jasonmerino** [comment]
Hey everyone. 

Sorry for the delay here. This has been on my radar and it looks like the time to fix this is here. I'm pretty slammed right now, would any of you be able to put together a PR with the changes needed. From what I can see, all that's needed is to change where we import AsyncStorage from in the index file here and update/add peer dependencies in the package.json so when installing it will complain if you try and install the current version with a new version of React Native. Also, some documentation about which version of simple store works with which version of React Native would be good to add to the README.

If no one can get to this right away I can try and carve out some time in the next month or so.

**Comment by oas** [comment]
If no one else already started, I can make the necessary changes tomorrow :)

**Comment by mikerodham** [comment]
I am slammed at work, may have some time over the weekend to get this looked at and sorted @oas but otherwise go ahead pal.

**Comment by tomtom94** [comment]
warning async storage has been extracted from react-native core

<img width="372" alt="Capture d’écran 2019-05-02 à 18 49 54" src="https://user-images.githubusercontent.com/262550/57092241-3901d500-6d0b-11e9-8ff1-4f81cbc7df71.png">

**Comment by raulccb** [comment]
> Eu sou golpeado no trabalho, pode ter algum tempo no fim de semana para obter este olhado e classificado @oas mas caso contrário vá em frente amigo.

I find this package very simple and efficient. It will be perfect if they manage to 0.59.4
I even recommended it to other friends

**Comment by raulccb** [comment]
> Hey everyone.
> 
> Sorry for the delay here. This has been on my radar and it looks like the time to fix this is here. I'm pretty slammed right now, would any of you be able to put together a PR with the changes needed. From what I can see, all that's needed is to change where we import AsyncStorage from in the index file here and update/add peer dependencies in the package.json so when installing it will complain if you try and install the current version with a new version of React Native. Also, some documentation about which version of simple store works with which version of React Native would be good to add to the README.
> 
> If no one can get to this right away I can try and carve out some time in the next month or so.

I find this package very simple and efficient. It will be perfect if they manage to 0.59.4
I even recommended it to other friends

**Comment by jasonmerino** [comment]
Version 2.0.0 has been released. This was resolved by #55.
